name: CI Build
on:
  push:
  pull_request:
    branches:
      - master
    paths-ignore:
    - 'README.md'

jobs:
  build:
    runs-on: ubuntu-latest
    # use a known build environment
    container: python:3.9-slim

    # Steps for the build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -e .[dev]

      - name: Linting
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 kanban --count --select=E9,F63,F7,F82 --show-source --statistics
          # The GitHub editor is 127 chars wide
          flake8 kanban --count --max-complexity=10 --max-line-length=127 --statistics

      - name: Run unit tests with nose
        run: nosetests

      - name: Upload code coverage
        uses: codecov/codecov-action@v2 
        with:
          version: "v0.1.13"   
